"""configuracion de horarios para la notaria

Revision ID: ac71da59b648
Revises: 8961515b3d47
Create Date: 2026-03-29 15:49:28.535305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac71da59b648'
down_revision = '8961515b3d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_horario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hora_apertura', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('hora_cierre', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('turno_manana_inicio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('turno_manana_fin', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('turno_tarde_inicio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('turno_tarde_fin', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('colacion_apertura', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('colacion_inicio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('colacion_fin', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('colacion_cierre', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dias_atencion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_sabado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sabado_inicio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sabado_fin', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('duracion_tramite', sa.Integer(), nullable=True))
        batch_op.alter_column('horario_apertura',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('horario_cierre',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_config', schema=None) as batch_op:
        batch_op.alter_column('horario_cierre',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('horario_apertura',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('duracion_tramite')
        batch_op.drop_column('sabado_fin')
        batch_op.drop_column('sabado_inicio')
        batch_op.drop_column('tipo_sabado')
        batch_op.drop_column('dias_atencion')
        batch_op.drop_column('colacion_cierre')
        batch_op.drop_column('colacion_fin')
        batch_op.drop_column('colacion_inicio')
        batch_op.drop_column('colacion_apertura')
        batch_op.drop_column('turno_tarde_fin')
        batch_op.drop_column('turno_tarde_inicio')
        batch_op.drop_column('turno_manana_fin')
        batch_op.drop_column('turno_manana_inicio')
        batch_op.drop_column('hora_cierre')
        batch_op.drop_column('hora_apertura')
        batch_op.drop_column('tipo_horario')

    # ### end Alembic commands ###
